package com.ehs.hiber.beans;
// Generated Jan 23, 2011 11:50:14 AM by Hibernate Tools 3.2.1.GA



/**
 * HistoryType generated by hbm2java
 */
public class HistoryType  implements java.io.Serializable {


     private int id;
     private String type;
     private String description;

    public HistoryType() {
    }

	
    public HistoryType(int id, String type) {
        this.id = id;
        this.type = type;
    }
    public HistoryType(int id, String type, String description) {
       this.id = id;
       this.type = type;
       this.description = description;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


