package com.ehs.hiber.beans;
// Generated Jan 23, 2011 11:50:14 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Medications generated by hbm2java
 */
public class Medications  implements java.io.Serializable {


     private int id;
     private String name;
     private String description;
     private String strengh;
     private String createdBy;
     private Date createdDate;
     private String updatedBy;
     private Date updatedDate;

    public Medications() {
    }

	
    public Medications(int id, String name, String createdBy, Date createdDate, String updatedBy, Date updatedDate) {
        this.id = id;
        this.name = name;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.updatedBy = updatedBy;
        this.updatedDate = updatedDate;
    }
    public Medications(int id, String name, String description, String strengh, String createdBy, Date createdDate, String updatedBy, Date updatedDate) {
       this.id = id;
       this.name = name;
       this.description = description;
       this.strengh = strengh;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.updatedBy = updatedBy;
       this.updatedDate = updatedDate;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getStrengh() {
        return this.strengh;
    }
    
    public void setStrengh(String strengh) {
        this.strengh = strengh;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


