package com.ehs.hiber.beans;
// Generated Jan 23, 2011 11:50:14 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Patient generated by hbm2java
 */
public class Patient  implements java.io.Serializable {


     private String medrecno;
     private int id;
     private String firstName;
     private String lastName;
     private String address;
     private String city;
     private Integer zipCode;
     private Integer homePhone;
     private Integer cellPhone;
     private String state;
     private char gender;
     private Date dateOfBirth;
     private String email;
     private int deleted;
     private String createdBy;
     private Date createdDate;
     private String updatedBy;
     private Date updatedDate;

    public Patient() {
    }

	
    public Patient(String medrecno, int id, String firstName, String lastName, char gender, int deleted, String createdBy, Date createdDate, Date updatedDate) {
        this.medrecno = medrecno;
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.gender = gender;
        this.deleted = deleted;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.updatedDate = updatedDate;
    }
    public Patient(String medrecno, int id, String firstName, String lastName, String address, String city, Integer zipCode, Integer homePhone, Integer cellPhone, String state, char gender, Date dateOfBirth, String email, int deleted, String createdBy, Date createdDate, String updatedBy, Date updatedDate) {
       this.medrecno = medrecno;
       this.id = id;
       this.firstName = firstName;
       this.lastName = lastName;
       this.address = address;
       this.city = city;
       this.zipCode = zipCode;
       this.homePhone = homePhone;
       this.cellPhone = cellPhone;
       this.state = state;
       this.gender = gender;
       this.dateOfBirth = dateOfBirth;
       this.email = email;
       this.deleted = deleted;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.updatedBy = updatedBy;
       this.updatedDate = updatedDate;
    }
   
    public String getMedrecno() {
        return this.medrecno;
    }
    
    public void setMedrecno(String medrecno) {
        this.medrecno = medrecno;
    }
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public Integer getZipCode() {
        return this.zipCode;
    }
    
    public void setZipCode(Integer zipCode) {
        this.zipCode = zipCode;
    }
    public Integer getHomePhone() {
        return this.homePhone;
    }
    
    public void setHomePhone(Integer homePhone) {
        this.homePhone = homePhone;
    }
    public Integer getCellPhone() {
        return this.cellPhone;
    }
    
    public void setCellPhone(Integer cellPhone) {
        this.cellPhone = cellPhone;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public char getGender() {
        return this.gender;
    }
    
    public void setGender(char gender) {
        this.gender = gender;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(int deleted) {
        this.deleted = deleted;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


