package com.ehs.hiber.beans;

// Generated Jan 23, 2011 11:50:14 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable, Comparable<Role> {

	private static final long serialVersionUID = -4018731129967930467L;
	
	private String roleId;
	private int id;
	private String name;
	private String description;
	private char active;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;
	private int deleted;

	public Role() {
	}

	public Role(String roleId, int id, String name, char active,
			String createdBy, Date createdDate, Date updatedDate, int deleted) {
		this.roleId = roleId;
		this.id = id;
		this.name = name;
		this.active = active;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.deleted = deleted;
	}

	public Role(String roleId, int id, String name, String description,
			char active, String createdBy, Date createdDate, String updatedBy,
			Date updatedDate, int deleted) {
		this.roleId = roleId;
		this.id = id;
		this.name = name;
		this.description = description;
		this.active = active;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.deleted = deleted;
	}

	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public char getActive() {
		return this.active;
	}

	public void setActive(char active) {
		this.active = active;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public int getDeleted() {
		return this.deleted;
	}

	public void setDeleted(int deleted) {
		this.deleted = deleted;
	}

	public String toString() {
		return name;
	}

	@Override
	public int compareTo(Role o) {
		return o.name.compareTo(name);
	}

}
