package com.ehs.hiber.beans;
// Generated Jan 23, 2011 11:50:14 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Specialization generated by hbm2java
 */
public class Specialization  implements java.io.Serializable {


     private String name;
     private int id;
     private String description;
     private String createdBy;
     private Date createdDate;
     private String updatedBy;
     private Date updateDate;

    public Specialization() {
    }

	
    public Specialization(String name, int id, String createdBy, Date createdDate, Date updateDate) {
        this.name = name;
        this.id = id;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.updateDate = updateDate;
    }
    public Specialization(String name, int id, String description, String createdBy, Date createdDate, String updatedBy, Date updateDate) {
       this.name = name;
       this.id = id;
       this.description = description;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.updatedBy = updatedBy;
       this.updateDate = updateDate;
    }
   
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }




}


