package com.ehs.hiber.beans;

// Generated Jan 23, 2011 11:50:14 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private static final long serialVersionUID = -2210371830622723807L;
	private String username;
	private int id;
	private String password;
	private String firstName;
	private String lastName;
	private char active;
	private int deleted;
	private String roldId;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;

	public User() {
	}

	public User(String username, int id, String password, String firstName,
			String lastName, char active, int deleted, String roldId,
			String createdBy, Date createdDate, Date updatedDate) {
		this.username = username;
		this.id = id;
		this.password = password;
		this.firstName = firstName;
		this.lastName = lastName;
		this.active = active;
		this.deleted = deleted;
		this.roldId = roldId;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	public User(String username, int id, String password, String firstName,
			String lastName, char active, int deleted, String roldId,
			String createdBy, Date createdDate, String updatedBy,
			Date updatedDate) {
		this.username = username;
		this.id = id;
		this.password = password;
		this.firstName = firstName;
		this.lastName = lastName;
		this.active = active;
		this.deleted = deleted;
		this.roldId = roldId;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public char getActive() {
		return this.active;
	}

	public void setActive(char active) {
		this.active = active;
	}

	public int getDeleted() {
		return this.deleted;
	}

	public void setDeleted(int deleted) {
		this.deleted = deleted;
	}

	public String getRoldId() {
		return this.roldId;
	}

	public void setRoldId(String roldId) {
		this.roldId = roldId;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	
    public boolean isValid() {
    	if(username == null || username.equals("")) {
    		return false;
    	}
    	
    	return true;
    }

}
