package com.ehs.hiber.beans;
// Generated Jan 23, 2011 11:50:14 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Doctor generated by hbm2java
 */
public class Doctor  implements java.io.Serializable {


     private String doctorId;
     private int id;
     private String firstName;
     private String lastName;
     private String address;
     private String city;
     private String state;
     private Integer zipCode;
     private Integer homePhone;
     private Integer cellPhone;
     private String email;
     private Integer fax;
     private String licenseNo;
     private String qualification;
     private char active;
     private int deleted;
     private String createdBy;
     private Date createdDate;
     private String updatedBy;
     private Date updatedDate;

    public Doctor() {
    }

	
    public Doctor(String doctorId, int id, String firstName, String lastName, char active, int deleted, String createdBy, Date createdDate, Date updatedDate) {
        this.doctorId = doctorId;
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.active = active;
        this.deleted = deleted;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.updatedDate = updatedDate;
    }
    public Doctor(String doctorId, int id, String firstName, String lastName, String address, String city, String state, Integer zipCode, Integer homePhone, Integer cellPhone, String email, Integer fax, String licenseNo, String qualification, char active, int deleted, String createdBy, Date createdDate, String updatedBy, Date updatedDate) {
       this.doctorId = doctorId;
       this.id = id;
       this.firstName = firstName;
       this.lastName = lastName;
       this.address = address;
       this.city = city;
       this.state = state;
       this.zipCode = zipCode;
       this.homePhone = homePhone;
       this.cellPhone = cellPhone;
       this.email = email;
       this.fax = fax;
       this.licenseNo = licenseNo;
       this.qualification = qualification;
       this.active = active;
       this.deleted = deleted;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.updatedBy = updatedBy;
       this.updatedDate = updatedDate;
    }
   
    public String getDoctorId() {
        return this.doctorId;
    }
    
    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId;
    }
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public Integer getZipCode() {
        return this.zipCode;
    }
    
    public void setZipCode(Integer zipCode) {
        this.zipCode = zipCode;
    }
    public Integer getHomePhone() {
        return this.homePhone;
    }
    
    public void setHomePhone(Integer homePhone) {
        this.homePhone = homePhone;
    }
    public Integer getCellPhone() {
        return this.cellPhone;
    }
    
    public void setCellPhone(Integer cellPhone) {
        this.cellPhone = cellPhone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getFax() {
        return this.fax;
    }
    
    public void setFax(Integer fax) {
        this.fax = fax;
    }
    public String getLicenseNo() {
        return this.licenseNo;
    }
    
    public void setLicenseNo(String licenseNo) {
        this.licenseNo = licenseNo;
    }
    public String getQualification() {
        return this.qualification;
    }
    
    public void setQualification(String qualification) {
        this.qualification = qualification;
    }
    public char getActive() {
        return this.active;
    }
    
    public void setActive(char active) {
        this.active = active;
    }
    public int getDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(int deleted) {
        this.deleted = deleted;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


