package com.ehs.hiber.beans;
// Generated Jan 23, 2011 11:50:14 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * History generated by hbm2java
 */
public class History  implements java.io.Serializable {


     private String historyTypeId;
     private int id;
     private int visitNo;
     private String medrecno;
     private String name;
     private String description;
     private Date startDate;
     private Date endDate;
     private String createdBy;
     private Date createdDate;
     private int deleted;
     private String updatedBy;
     private Date updatedDate;

    public History() {
    }

	
    public History(String historyTypeId, int id, int visitNo, String medrecno, String name, Date startDate, Date endDate, String createdBy, Date createdDate, int deleted, Date updatedDate) {
        this.historyTypeId = historyTypeId;
        this.id = id;
        this.visitNo = visitNo;
        this.medrecno = medrecno;
        this.name = name;
        this.startDate = startDate;
        this.endDate = endDate;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.deleted = deleted;
        this.updatedDate = updatedDate;
    }
    public History(String historyTypeId, int id, int visitNo, String medrecno, String name, String description, Date startDate, Date endDate, String createdBy, Date createdDate, int deleted, String updatedBy, Date updatedDate) {
       this.historyTypeId = historyTypeId;
       this.id = id;
       this.visitNo = visitNo;
       this.medrecno = medrecno;
       this.name = name;
       this.description = description;
       this.startDate = startDate;
       this.endDate = endDate;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.deleted = deleted;
       this.updatedBy = updatedBy;
       this.updatedDate = updatedDate;
    }
   
    public String getHistoryTypeId() {
        return this.historyTypeId;
    }
    
    public void setHistoryTypeId(String historyTypeId) {
        this.historyTypeId = historyTypeId;
    }
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getVisitNo() {
        return this.visitNo;
    }
    
    public void setVisitNo(int visitNo) {
        this.visitNo = visitNo;
    }
    public String getMedrecno() {
        return this.medrecno;
    }
    
    public void setMedrecno(String medrecno) {
        this.medrecno = medrecno;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public int getDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(int deleted) {
        this.deleted = deleted;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


