package com.ehs.hiber.beans;
// Generated Jan 23, 2011 11:50:14 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Labrecords generated by hbm2java
 */
public class Labrecords  implements java.io.Serializable {


     private int id;
     private String typeId;
     private int visitNo;
     private String medrecno;
     private String description;
     private int deleted;
     private String createdBy;
     private Date createdDate;
     private String updatedBy;
     private Date updatedDate;

    public Labrecords() {
    }

	
    public Labrecords(int id, String typeId, int visitNo, String medrecno, int deleted, String createdBy, Date createdDate, Date updatedDate) {
        this.id = id;
        this.typeId = typeId;
        this.visitNo = visitNo;
        this.medrecno = medrecno;
        this.deleted = deleted;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.updatedDate = updatedDate;
    }
    public Labrecords(int id, String typeId, int visitNo, String medrecno, String description, int deleted, String createdBy, Date createdDate, String updatedBy, Date updatedDate) {
       this.id = id;
       this.typeId = typeId;
       this.visitNo = visitNo;
       this.medrecno = medrecno;
       this.description = description;
       this.deleted = deleted;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.updatedBy = updatedBy;
       this.updatedDate = updatedDate;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }
    public int getVisitNo() {
        return this.visitNo;
    }
    
    public void setVisitNo(int visitNo) {
        this.visitNo = visitNo;
    }
    public String getMedrecno() {
        return this.medrecno;
    }
    
    public void setMedrecno(String medrecno) {
        this.medrecno = medrecno;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public int getDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(int deleted) {
        this.deleted = deleted;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


