package com.ehs.hiber.beans;
// Generated Jan 23, 2011 11:50:14 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Visit generated by hbm2java
 */
public class Visit  implements java.io.Serializable {


     private int visitNo;
     private int id;
     private String medrecno;
     private Date visitDate;
     private String doctorId;
     private String reason;
     private String familyDoctorId;
     private int deleted;
     private String createdBy;
     private Date createdDate;
     private String updatedBy;
     private Date updatedDate;

    public Visit() {
    }

	
    public Visit(int visitNo, int id, String medrecno, Date visitDate, String doctorId, int deleted, String createdBy, Date createdDate, Date updatedDate) {
        this.visitNo = visitNo;
        this.id = id;
        this.medrecno = medrecno;
        this.visitDate = visitDate;
        this.doctorId = doctorId;
        this.deleted = deleted;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.updatedDate = updatedDate;
    }
    public Visit(int visitNo, int id, String medrecno, Date visitDate, String doctorId, String reason, String familyDoctorId, int deleted, String createdBy, Date createdDate, String updatedBy, Date updatedDate) {
       this.visitNo = visitNo;
       this.id = id;
       this.medrecno = medrecno;
       this.visitDate = visitDate;
       this.doctorId = doctorId;
       this.reason = reason;
       this.familyDoctorId = familyDoctorId;
       this.deleted = deleted;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.updatedBy = updatedBy;
       this.updatedDate = updatedDate;
    }
   
    public int getVisitNo() {
        return this.visitNo;
    }
    
    public void setVisitNo(int visitNo) {
        this.visitNo = visitNo;
    }
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getMedrecno() {
        return this.medrecno;
    }
    
    public void setMedrecno(String medrecno) {
        this.medrecno = medrecno;
    }
    public Date getVisitDate() {
        return this.visitDate;
    }
    
    public void setVisitDate(Date visitDate) {
        this.visitDate = visitDate;
    }
    public String getDoctorId() {
        return this.doctorId;
    }
    
    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public String getFamilyDoctorId() {
        return this.familyDoctorId;
    }
    
    public void setFamilyDoctorId(String familyDoctorId) {
        this.familyDoctorId = familyDoctorId;
    }
    public int getDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(int deleted) {
        this.deleted = deleted;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


