SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`USER` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`USER` (
  `ID` INT NOT NULL ,
  `ROLE_ID` INT NOT NULL ,
  `USERNAME` VARCHAR(50) NOT NULL ,
  `PASSWORD` VARCHAR(50) NOT NULL ,
  `FNAME` VARCHAR(50) NOT NULL ,
  `LNAME` VARCHAR(50) NOT NULL ,
  `ACTIVE` INT NOT NULL DEFAULT 0 ,
  `DELETED` INT NOT NULL DEFAULT 0 ,
  `CREATED_BY` INT NOT NULL ,
  `CREATED_DATE` TIMESTAMP NOT NULL ,
  `UPDATED_BY` INT NOT NULL ,
  
  PRIMARY KEY (`ID`) ,
  INDEX `fk_USER_ROLE1` (`ROLE_ID` ASC) ,
  INDEX `fk_USER_USER1` (`CREATED_BY` ASC) ,
  INDEX `fk_USER_USER2` (`UPDATED_BY` ASC) ,
  CONSTRAINT `fk_USER_ROLE1`
    FOREIGN KEY (`ROLE_ID` )
    REFERENCES `mydb`.`ROLE` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_USER1`
    FOREIGN KEY (`CREATED_BY` )
    REFERENCES `mydb`.`USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_USER2`
    FOREIGN KEY (`UPDATED_BY` )
    REFERENCES `mydb`.`USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ROLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ROLE` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`ROLE` (
  `ID` INT NOT NULL ,
  `NAME` VARCHAR(50) NOT NULL ,
  `DESCRIPTION` VARCHAR(50) NULL ,
  `ACTIVE` INT NOT NULL DEFAULT 0 ,
  `DELETED` INT NOT NULL DEFAULT 0 ,
  `CREATED_BY` INT NOT NULL ,
  `CREATED_DATE` TIMESTAMP NOT NULL ,
  `UPDATED_BY` INT NOT NULL ,
  
  PRIMARY KEY (`ID`) ,
  INDEX `fk_ROLE_USER1` (`CREATED_BY` ASC) ,
  INDEX `fk_ROLE_USER2` (`UPDATED_BY` ASC) ,
  CONSTRAINT `fk_ROLE_USER1`
    FOREIGN KEY (`CREATED_BY` )
    REFERENCES `mydb`.`USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ROLE_USER2`
    FOREIGN KEY (`UPDATED_BY` )
    REFERENCES `mydb`.`USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PATIENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PATIENT` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`PATIENT` (
  `ID` INT NOT NULL ,
  `TITLE` VARCHAR(5) NULL ,
  `MEDRECNO` VARCHAR(12) NOT NULL ,
  `FNAME` VARCHAR(50) NOT NULL ,
  `LNAME` VARCHAR(50) NOT NULL ,
  `HOME_PHONE` INT NULL ,
  `ADDRESS` VARCHAR(100) NULL ,
  `CITY` VARCHAR(25) NULL ,
  `PIN` INT NULL ,
  `CELL_PHONE` INT NULL ,
  `GENDER` VARCHAR(1) NULL ,
  `WEIGHT` FLOAT NOT NULL ,
  `HEIGHT` FLOAT NULL ,
  `DATE_OF_BIRTH` DATE NULL ,
  `AGE` INT NOT NULL ,
  `EMAIL` VARCHAR(50) NULL ,
  `STATE` VARCHAR(50) NULL ,
  `DELETED` INT NULL DEFAULT 0 ,
  `CREATED_BY` INT NOT NULL ,
  `CREATED_DATE` TIMESTAMP NOT NULL ,
  `LAST_UPDATED_BY` INT NOT NULL ,
  
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX `MEDRECNO_UNIQUE` (`MEDRECNO` ASC) ,
  INDEX `fk_PATIENT_USER1` (`CREATED_BY` ASC) ,
  INDEX `fk_PATIENT_USER2` (`LAST_UPDATED_BY` ASC) ,
  CONSTRAINT `fk_PATIENT_USER1`
    FOREIGN KEY (`CREATED_BY` )
    REFERENCES `mydb`.`USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PATIENT_USER2`
    FOREIGN KEY (`LAST_UPDATED_BY` )
    REFERENCES `mydb`.`USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SPECIALIZATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SPECIALIZATION` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`SPECIALIZATION` (
  `ID` INT NOT NULL ,
  `NAME` VARCHAR(45) NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DOCTOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DOCTOR` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`DOCTOR` (
  `ID` INT NOT NULL ,
  `DOCTOR_ID` INT NOT NULL ,
  `TITLE` VARCHAR(5) NULL ,
  `FNAME` VARCHAR(50) NOT NULL ,
  `LNAME` VARCHAR(50) NOT NULL ,
  `HOME_PHONE` VARCHAR(10) NULL ,
  `ADDRESS` VARCHAR(100) NULL ,
  `CITY` VARCHAR(25) NULL ,
  `PIN` INT NULL ,
  `QUALIFICATION` VARCHAR(40) NULL ,
  `SPECIALIZATION_ID` INT NULL ,
  `CELL_PHONE` INT NULL ,
  `FAX` INT NULL ,
  `LICENSE_NO` VARCHAR(15) NULL ,
  `QUALIFICATION` VARCHAR(40) NOT NULL ,
  `ACTIVE` INT NOT NULL DEFAULT 0 ,
  `DELETED` INT NOT NULL DEFAULT 0 ,
  `CREATED_BY` INT NOT NULL ,
  `CREATED_DATE` TIMESTAMP NOT NULL ,
  `UPDATED_BY` INT NOT NULL ,
  `DELETED` INT NULL DEFAULT 0 ,
  PRIMARY KEY (`ID`) ,
  INDEX `fk_DOCTOR_SPECIALIZATION1` (`SPECIALIZATION_ID` ASC) ,
  UNIQUE INDEX `DOCTOR_ID_UNIQUE` (`DOCTOR_ID` ASC) ,
  INDEX `fk_DOCTOR_USER1` (`CREATED_BY` ASC) ,
  INDEX `fk_DOCTOR_USER2` (`UPDATED_BY` ASC) ,
  CONSTRAINT `fk_DOCTOR_SPECIALIZATION1`
    FOREIGN KEY (`SPECIALIZATION_ID` )
    REFERENCES `mydb`.`SPECIALIZATION` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DOCTOR_USER1`
    FOREIGN KEY (`CREATED_BY` )
    REFERENCES `mydb`.`USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DOCTOR_USER2`
    FOREIGN KEY (`UPDATED_BY` )
    REFERENCES `mydb`.`USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BIOMETRICS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`BIOMETRICS` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`BIOMETRICS` (
  `ID` INT NOT NULL ,
  `HEIGHT` DECIMAL(5,2) NULL ,
  `WEIGHT` DECIMAL(5,2) NULL ,
  `TEMPERATURE` DECIMAL(5,2) NULL ,
  `HEART_RATE` DECIMAL(5,2) NULL ,
  `BLOOD_PRESSURE` DECIMAL(5,2) NULL ,
  `DATE` DATETIME NULL ,
  `PROCESSED _BY` VARCHAR(45) NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ASSISTANT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ASSISTANT` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`ASSISTANT` (
  `ID` INT NOT NULL ,
  `FNAME` VARCHAR(50) NOT NULL ,
  `LNAME` VARCHAR(50) NOT NULL ,
  `GENDER` CHAR NOT NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PAYMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PAYMENT` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`PAYMENT` (
  `ID` INT NOT NULL ,
  `ASSISTANT_ID` INT NOT NULL ,
  `AMOUT` DECIMAL(5,2) NULL ,
  `DATE` DATETIME NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `fk_PAYMENT_ASSISTANT1` (`ASSISTANT_ID` ASC) ,
  CONSTRAINT `fk_PAYMENT_ASSISTANT1`
    FOREIGN KEY (`ASSISTANT_ID` )
    REFERENCES `mydb`.`ASSISTANT` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VISITATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`VISIT` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`VISIT` (
  `ID` INT NOT NULL ,
  `MERECNO` INT NOT NULL ,
  `DOCTOR_ID` INT NOT NULL ,
  `BIOMETRICS_ID` INT NULL ,
  `VISIT_NO` INT NOT NULL ,
  `PAYMENT_ID` INT NULL ,
  `REASON` VARCHAR(80) NULL ,
  `DELETED` INT NULL DEFAULT 0 ,
  `CREATED_BY` INT NOT NULL ,
  `CREATED_DATE` TIMESTAMP NOT NULL ,
  `UPDATED_BY` INT NOT NULL ,
  `UPDATED_DATE` DATETIME NOT NULL ,
  PRIMARY KEY (`ID`, `PATIENT_ID`, `DOCTOR_ID`) ,
  INDEX `fk_PATIENT_has_DOCTOR_DOCTOR1` (`DOCTOR_ID` ASC) ,
  INDEX `fk_PATIENT_has_DOCTOR_BIOMETRICS1` (`BIOMETRICS_ID` ASC) ,
  INDEX `fk_PATIENT_has_DOCTOR_PAYMENT1` (`PAYMENT_ID` ASC) ,
  UNIQUE INDEX `VISIT_NO_UNIQUE` (`VISIT_NO` ASC) ,
  INDEX `fk_VISITION_USER1` (`CREATED_BY` ASC) ,
  INDEX `fk_VISITION_USER1` (`UPDATED_BY` ASC) ,
  CONSTRAINT `fk_PATIENT_has_DOCTOR_PATIENT`
    FOREIGN KEY (`PATIENT_ID` )
    REFERENCES `mydb`.`PATIENT` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PATIENT_has_DOCTOR_DOCTOR1`
    FOREIGN KEY (`DOCTOR_ID` )
    REFERENCES `mydb`.`DOCTOR` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PATIENT_has_DOCTOR_BIOMETRICS1`
    FOREIGN KEY (`BIOMETRICS_ID` )
    REFERENCES `mydb`.`BIOMETRICS` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PATIENT_has_DOCTOR_PAYMENT1`
    FOREIGN KEY (`PAYMENT_ID` )
    REFERENCES `mydb`.`PAYMENT` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VISITION_USER1`
    FOREIGN KEY (`CREATED_BY` )
    REFERENCES `mydb`.`USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VISITION_USER1`
    FOREIGN KEY (`UPDATED_BY` )
    REFERENCES `mydb`.`USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PATIENT_has_ASSISTANT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PATIENT_has_ASSISTANT` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`PATIENT_has_ASSISTANT` (
  `PATIENT_ID` INT NOT NULL ,
  `ASSISTANT_ID` INT NOT NULL ,
  `DATE` DATETIME NOT NULL ,
  `DETAILS` VARCHAR(80) NULL ,
  PRIMARY KEY (`PATIENT_ID`, `ASSISTANT_ID`) ,
  INDEX `fk_PATIENT_has_ASSISTANT_ASSISTANT1` (`ASSISTANT_ID` ASC) ,
  CONSTRAINT `fk_PATIENT_has_ASSISTANT_PATIENT1`
    FOREIGN KEY (`PATIENT_ID` )
    REFERENCES `mydb`.`PATIENT` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PATIENT_has_ASSISTANT_ASSISTANT1`
    FOREIGN KEY (`ASSISTANT_ID` )
    REFERENCES `mydb`.`ASSISTANT` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HISTORY_TYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`HISTORY_TYPE` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`HISTORY_TYPE` (
  `ID` INT NOT NULL ,
  `TYPE` VARCHAR(10) NOT NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HISTORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`HISTORY` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`HISTORY` (
  `ID` INT NOT NULL ,
  `HISTORY_TYPE_ID` INT NOT NULL ,
  `PATIENT_ID` INT NOT NULL ,
  `DATE` DATETIME NULL ,
  `DESC` VARCHAR(45) NULL ,
  `VISITATION_ID` INT NOT NULL ,
  `VISITATION_PATIENT_ID` INT NOT NULL ,
  `VISITATION_DOCTOR_ID` INT NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `fk_HISTORY_HISTORY_TYPE1` (`HISTORY_TYPE_ID` ASC) ,
  INDEX `fk_HISTORY_PATIENT1` (`PATIENT_ID` ASC) ,
  INDEX `fk_HISTORY_VISITATION1` (`VISITATION_ID` ASC, `VISITATION_PATIENT_ID` ASC, `VISITATION_DOCTOR_ID` ASC) ,
  CONSTRAINT `fk_HISTORY_HISTORY_TYPE1`
    FOREIGN KEY (`HISTORY_TYPE_ID` )
    REFERENCES `mydb`.`HISTORY_TYPE` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HISTORY_PATIENT1`
    FOREIGN KEY (`PATIENT_ID` )
    REFERENCES `mydb`.`PATIENT` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HISTORY_VISITATION1`
    FOREIGN KEY (`VISITATION_ID` , `VISITATION_PATIENT_ID` , `VISITATION_DOCTOR_ID` )
    REFERENCES `mydb`.`VISITATION` (`ID` , `PATIENT_ID` , `DOCTOR_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRESCRIPTION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PRESCRIPTION` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`PRESCRIPTION` (
  `ID` INT NOT NULL ,
  `VISITATION_ID` INT NOT NULL ,
  `NAME` VARCHAR(40) NULL ,
  `DESC` VARCHAR(45) NULL ,
  `DATE` DATETIME NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `fk_PRESCRIPTION_PATIENT_has_DOCTOR1` (`VISITATION_ID` ASC) ,
  CONSTRAINT `fk_PRESCRIPTION_PATIENT_has_DOCTOR1`
    FOREIGN KEY (`VISITATION_ID` )
    REFERENCES `mydb`.`VISITATION` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NOTES_TYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`NOTES_TYPE` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`NOTES_TYPE` (
  `ID` INT NOT NULL ,
  `TYPE` VARCHAR(10) NOT NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NOTES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`NOTES` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`NOTES` (
  `ID` INT NOT NULL ,
  `VISITATION` INT NULL ,
  `PATIENT_ID` INT NULL ,
  `NOTES_TYPE_ID` INT NULL ,
  `DOCTOR_ID` INT NULL ,
  `ASSISTANT_ID` INT NULL ,
  `DESC` VARCHAR(80) NULL ,
  `DATE` DATETIME NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `fk_NOTES_PATIENT_has_DOCTOR1` (`VISITATION` ASC) ,
  INDEX `fk_NOTES_PATIENT1` (`PATIENT_ID` ASC) ,
  INDEX `fk_NOTES_NOTES_TYPE1` (`NOTES_TYPE_ID` ASC) ,
  INDEX `fk_NOTES_DOCTOR1` (`DOCTOR_ID` ASC) ,
  INDEX `fk_NOTES_ASSISTANT1` (`ASSISTANT_ID` ASC) ,
  CONSTRAINT `fk_NOTES_PATIENT_has_DOCTOR1`
    FOREIGN KEY (`VISITATION` )
    REFERENCES `mydb`.`VISITATION` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NOTES_PATIENT1`
    FOREIGN KEY (`PATIENT_ID` )
    REFERENCES `mydb`.`PATIENT` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NOTES_NOTES_TYPE1`
    FOREIGN KEY (`NOTES_TYPE_ID` )
    REFERENCES `mydb`.`NOTES_TYPE` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NOTES_DOCTOR1`
    FOREIGN KEY (`DOCTOR_ID` )
    REFERENCES `mydb`.`DOCTOR` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NOTES_ASSISTANT1`
    FOREIGN KEY (`ASSISTANT_ID` )
    REFERENCES `mydb`.`ASSISTANT` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LABRECORDS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`LABRECORDS` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`LABRECORDS` (
  `ID` INT NOT NULL ,
  `VISITATION_ID` INT NOT NULL ,
  PRIMARY KEY (`ID`, `VISITATION_ID`) ,
  INDEX `fk_LABRECORDS_PATIENT_has_DOCTOR1` (`VISITATION_ID` ASC) ,
  CONSTRAINT `fk_LABRECORDS_PATIENT_has_DOCTOR1`
    FOREIGN KEY (`VISITATION_ID` )
    REFERENCES `mydb`.`VISITATION` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MEDICATIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MEDICATIONS` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`MEDICATIONS` (
  `ID` INT NOT NULL ,
  `PRESCRIPTION_ID` INT NOT NULL ,
  `NAME` VARCHAR(45) NULL ,
  `DESC` VARCHAR(45) NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `fk_MEDICAL_RECORDS_PRESCRIPTION1` (`PRESCRIPTION_ID` ASC) ,
  CONSTRAINT `fk_MEDICAL_RECORDS_PRESCRIPTION1`
    FOREIGN KEY (`PRESCRIPTION_ID` )
    REFERENCES `mydb`.`PRESCRIPTION` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LAB_TYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`LAB_TYPE` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`LAB_TYPE` (
  `LAB_TYPE` INT NOT NULL ,
  `LABRECORDS_ID` INT NOT NULL ,
  PRIMARY KEY (`LAB_TYPE`) ,
  INDEX `fk_LAB_TYPE_LABRECORDS1` (`LABRECORDS_ID` ASC) ,
  CONSTRAINT `fk_LAB_TYPE_LABRECORDS1`
    FOREIGN KEY (`LABRECORDS_ID` )
    REFERENCES `mydb`.`LABRECORDS` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
